INSERT INTO userType_list(userTypeName) VALUES
("Student"),
("Admin_00"),
("Developer");

INSERT INTO gender_list(genderName) VALUES
("Male"),
("Female");

INSERT INTO marital_list(maritalName) VALUES
("Single"),
("Married"),
("Separated"),
("Divorced"),
("Widowed");

INSERT INTO religion_list(religionName) VALUES
("Islam"),
("Buddhism"),
("Hinduism"),
("Christianity"),
("Others");

INSERT INTO state_list(stateName) VALUES
("Johor"),
("Kedah"),
("Kelantan"),
("Melaka"),
("Negeri Sembilan"),
("Pahang"),
("Perak"),
("Perlis"),
("Pulau Pinang"),
("Sabah"),
("Sarawak"),
("Selangor"),
("Terengganu"),
("W.P. Kuala Lumpur"),
("W.P. Labuan"),
("W.P. Putrajaya"),
("Others");

INSERT INTO ethnicity_list(ethnicityName) VALUES
("Malay"),
("Orang Asli"),
("Bumiputera Sabah"),
("Bumiputera Sarawak"),
("Chinese"),
("Indian"),
("Others");

INSERT INTO studyLevel_list(studyLevelName) VALUES
("Professional Qualification"),
("Bachelor’s Degree"),
("Master’s Degree"),
("Doctorate");

INSERT INTO country_list(countryName) VALUES
("United Kingdom"),
("Ireland");

INSERT INTO postTown_list(countryCode, postTownName) VALUES
(1, "Abbots Langley"),
(1, "Aberaeron"),
(1, "Aberdare"),
(1, "Aberdeen"),
(1, "Aberdovey"),
(1, "Aberfeldy"),
(1, "Abergavenny"),
(1, "Abergele"),
(1, "Aberlour"),
(1, "Abertillery"),
(1, "Aberystwyth"),
(1, "Abingdon"),
(1, "Aboyne"),
(1, "Accrington"),
(1, "Acharacle"),
(1, "Achnasheen"),
(1, "Addlestone"),
(1, "Airdrie"),
(1, "Alcester"),
(1, "Aldeburgh"),
(1, "Alderley Edge"),
(1, "Aldershot"),
(1, "Alexandria"),
(1, "Alford"),
(1, "Alfreton"),
(1, "Alloa"),
(1, "Alness"),
(1, "Alnwick"),
(1, "Alresford"),
(1, "Alston"),
(1, "Alton"),
(1, "Altrincham"),
(1, "Alva"),
(1, "Ambleside"),
(1, "Amersham"),
(1, "Amlwch"),
(1, "Ammanford"),
(1, "Andover"),
(1, "Annan"),
(1, "Anstruther"),
(1, "Antrim"),
(1, "Appin"),
(1, "Appleby-in-Westmorland"),
(1, "Arbroath"),
(1, "Ardgay"),
(1, "Arisaig"),
(1, "Arlesey"),
(1, "Armagh"),
(1, "Arrochar"),
(1, "Arthog"),
(1, "Arundel"),
(1, "Ascot"),
(1, "Ashbourne"),
(1, "Ashby-de-La-Zouch"),
(1, "Ashford"),
(1, "Ashington"),
(1, "Ashtead"),
(1, "Ashton-under-Lyne"),
(1, "Askam-in-Furness"),
(1, "Atherstone"),
(1, "Attleborough"),
(1, "Auchterarder"),
(1, "Augher"),
(1, "Aughnacloy"),
(1, "Aviemore"),
(1, "Avoch"),
(1, "Axbridge"),
(1, "Axminster"),
(1, "Aylesbury"),
(1, "Aylesford"),
(1, "Ayr"),
(1, "Bacup"),
(1, "Badminton"),
(1, "Bagillt"),
(1, "Bagshot"),
(1, "Bakewell"),
(1, "Bala"),
(1, "Baldock"),
(1, "Balerno"),
(1, "Ballachulish"),
(1, "Ballater"),
(1, "Ballindalloch"),
(1, "Ballycastle"),
(1, "Ballyclare"),
(1, "Ballymena"),
(1, "Ballymoney"),
(1, "Ballynahinch"),
(1, "Bamburgh"),
(1, "Bampton"),
(1, "Banbridge"),
(1, "Banbury"),
(1, "Banchory"),
(1, "Banff"),
(1, "Bangor"),
(1, "Banstead"),
(1, "Banwell"),
(1, "Bargoed"),
(1, "Barking"),
(1, "Barmouth"),
(1, "Barnard Castle"),
(1, "Barnet"),
(1, "Barnetby"),
(1, "Barnoldswick"),
(1, "Barnsley"),
(1, "Barnstaple"),
(1, "Barrow-in-Furness"),
(1, "Barrow-upon-Humber"),
(1, "Barry"),
(1, "Barton-upon-Humber"),
(1, "Basildon"),
(1, "Basingstoke"),
(1, "Bath"),
(1, "Bathgate"),
(1, "Batley"),
(1, "Battle"),
(1, "Beaconsfield"),
(1, "Beaminster"),
(1, "Beauly"),
(1, "Beaumaris"),
(1, "Beaworthy"),
(1, "Beccles"),
(1, "Beckenham"),
(1, "Beckermet"),
(1, "Bedale"),
(1, "Bedford"),
(1, "Bedlington"),
(1, "Bedworth"),
(1, "Belfast"),
(1, "Belford"),
(1, "Bellshill"),
(1, "Belper"),
(1, "Belvedere"),
(1, "Bembridge"),
(1, "Benfleet"),
(1, "Berkeley"),
(1, "Berkhamsted"),
(1, "Berriedale"),
(1, "Berwick-upon-Tweed"),
(1, "Betchworth"),
(1, "Betws-y-Coed"),
(1, "Beverley"),
(1, "Bewdley"),
(1, "Bexhill-on-Sea"),
(1, "Bexley"),
(1, "Bexleyheath"),
(1, "Bicester"),
(1, "Bideford"),
(1, "Biggar"),
(1, "Biggleswade"),
(1, "Billericay"),
(1, "Billingham"),
(1, "Billingshurst"),
(1, "Bilston"),
(1, "Bingley"),
(1, "Birchington"),
(1, "Birkenhead"),
(1, "Birmingham"),
(1, "Bishop Auckland"),
(1, "Bishops Castle"),
(1, "Bishop's Stortford"),
(1, "Bishopton"),
(1, "Blackburn"),
(1, "Blackpool"),
(1, "Blackwood"),
(1, "Blaenau Ffestiniog"),
(1, "Blairgowrie"),
(1, "Blakeney"),
(1, "Blandford Forum"),
(1, "Blaydon-on-Tyne"),
(1, "Blyth"),
(1, "Boat of Garten"),
(1, "Bodmin"),
(1, "Bodorgan"),
(1, "Bognor Regis"),
(1, "Boldon Colliery"),
(1, "Bolton"),
(1, "Boncath"),
(1, "Bo'Ness"),
(1, "Bonnybridge"),
(1, "Bonnyrigg"),
(1, "Bootle"),
(1, "Bordon"),
(1, "Borehamwood"),
(1, "Borth"),
(1, "Boscastle"),
(1, "Boston"),
(1, "Bourne"),
(1, "Bourne End"),
(1, "Bournemouth"),
(1, "Bow Street"),
(1, "Brackley"),
(1, "Bracknell"),
(1, "Bradford"),
(1, "Bradford-on-Avon"),
(1, "Braintree"),
(1, "Brampton"),
(1, "Brandon"),
(1, "Braunton"),
(1, "Brechin"),
(1, "Brecon"),
(1, "Brentford"),
(1, "Brentwood"),
(1, "Bridge of Orchy"),
(1, "Bridge of Weir"),
(1, "Bridgend"),
(1, "Bridgnorth"),
(1, "Bridgwater"),
(1, "Bridlington"),
(1, "Bridport"),
(1, "Brierley Hill"),
(1, "Brigg"),
(1, "Brighouse"),
(1, "Brighton"),
(1, "Bristol"),
(1, "Brixham"),
(1, "Broadstairs"),
(1, "Broadstone"),
(1, "Broadway"),
(1, "Brockenhurst"),
(1, "Bromley"),
(1, "Bromsgrove"),
(1, "Bromyard"),
(1, "Brora"),
(1, "Broseley"),
(1, "Brough"),
(1, "Broughton-in-Furness"),
(1, "Broxbourne"),
(1, "Broxburn"),
(1, "Bruton"),
(1, "Brynteg"),
(1, "Buckfastleigh"),
(1, "Buckhurst Hill"),
(1, "Buckie"),
(1, "Buckingham"),
(1, "Buckley"),
(1, "Bucknell"),
(1, "Bude"),
(1, "Budleigh Salterton"),
(1, "Builth Wells"),
(1, "Bungay"),
(1, "Buntingford"),
(1, "Bures"),
(1, "Burford"),
(1, "Burnham-on-Crouch"),
(1, "Burnham-on-Sea"),
(1, "Burnley"),
(1, "Burntisland"),
(1, "Burntwood"),
(1, "Burry Port"),
(1, "Burton-on-Trent"),
(1, "Bury"),
(1, "Bury St. Edmunds"),
(1, "Bushey"),
(1, "Bushmills"),
(1, "Buxton"),
(1, "Caernarfon"),
(1, "Caerphilly"),
(1, "Caersws"),
(1, "Cairndow"),
(1, "Caldicot"),
(1, "Caledon"),
(1, "Callander"),
(1, "Callington"),
(1, "Calne"),
(1, "Calstock"),
(1, "Camberley"),
(1, "Camborne"),
(1, "Cambridge"),
(1, "Camelford"),
(1, "Campbeltown"),
(1, "Cannock"),
(1, "Canonbie"),
(1, "Canterbury"),
(1, "Canvey Island"),
(1, "Cardiff"),
(1, "Cardigan"),
(1, "Carlisle"),
(1, "Carluke"),
(1, "Carmarthen"),
(1, "Carnforth"),
(1, "Carnoustie"),
(1, "Carrbridge"),
(1, "Carrickfergus"),
(1, "Carshalton"),
(1, "Carterton"),
(1, "Castle Cary"),
(1, "Castle Douglas"),
(1, "Castlederg"),
(1, "Castleford"),
(1, "Castlewellan"),
(1, "Caterham"),
(1, "Catterick Garrison"),
(1, "Cemaes Bay"),
(1, "Chalfont St. Giles"),
(1, "Chard"),
(1, "Chatham"),
(1, "Chathill"),
(1, "Chatteris"),
(1, "Cheadle"),
(1, "Cheddar"),
(1, "Chelmsford"),
(1, "Cheltenham"),
(1, "Chepstow"),
(1, "Chertsey"),
(1, "Chesham"),
(1, "Chessington"),
(1, "Chester"),
(1, "Chester le Street"),
(1, "Chesterfield"),
(1, "Chichester"),
(1, "Chigwell"),
(1, "Chinnor"),
(1, "Chippenham"),
(1, "Chipping Campden"),
(1, "Chipping Norton"),
(1, "Chislehurst"),
(1, "Choppington"),
(1, "Chorley"),
(1, "Christchurch"),
(1, "Chulmleigh"),
(1, "Church Stretton"),
(1, "Cinderford"),
(1, "Cirencester"),
(1, "Clackmannan"),
(1, "Clacton-on-Sea"),
(1, "Clarbeston Road"),
(1, "Cleator"),
(1, "Cleator Moor"),
(1, "Cleckheaton"),
(1, "Cleethorpes"),
(1, "Clevedon"),
(1, "Clitheroe"),
(1, "Clogher"),
(1, "Clydebank"),
(1, "Clynderwen"),
(1, "Coalville"),
(1, "Coatbridge"),
(1, "Cobham"),
(1, "Cockburnspath"),
(1, "Cockermouth"),
(1, "Colchester"),
(1, "Coldstream"),
(1, "Coleford"),
(1, "Coleraine"),
(1, "Colintraive"),
(1, "Colne"),
(1, "Colwyn Bay"),
(1, "Colyton"),
(1, "Congleton"),
(1, "Coniston"),
(1, "Consett"),
(1, "Conwy"),
(1, "Cookstown"),
(1, "Corbridge"),
(1, "Corby"),
(1, "Cornhill-on-Tweed"),
(1, "Corrour"),
(1, "Corsham"),
(1, "Corwen"),
(1, "Cottingham"),
(1, "Coulsdon"),
(1, "Coventry"),
(1, "Coventry N&W Satellite Villages"),
(1, "Coventry Southern Satellite Villages & Kenilworth"),
(1, "Cowbridge"),
(1, "Cowdenbeath"),
(1, "Cowes"),
(1, "Cradley Heath"),
(1, "Craigavon"),
(1, "Cramlington"),
(1, "Cranbrook"),
(1, "Cranleigh"),
(1, "Craven Arms"),
(1, "Crawley"),
(1, "Crediton"),
(1, "Crewe"),
(1, "Crewkerne"),
(1, "Crianlarich"),
(1, "Criccieth"),
(1, "Crickhowell"),
(1, "Crieff"),
(1, "Cromarty"),
(1, "Cromer"),
(1, "Crook"),
(1, "Crowborough"),
(1, "Crowthorne"),
(1, "Croydon"),
(1, "Crumlin"),
(1, "Crymych"),
(1, "Cullompton"),
(1, "Cumnock"),
(1, "Cupar"),
(1, "Currie"),
(1, "Cwmbran"),
(1, "Dagenham"),
(1, "Dalbeattie"),
(1, "Dalkeith"),
(1, "Dalmally"),
(1, "Dalton-in-Furness"),
(1, "Dalwhinnie"),
(1, "Darlington"),
(1, "Dartford"),
(1, "Dartmouth"),
(1, "Darvel"),
(1, "Darwen"),
(1, "Daventry"),
(1, "Dawlish"),
(1, "Deal"),
(1, "Deeside"),
(1, "Delabole"),
(1, "Denbigh"),
(1, "Denny"),
(1, "Derby"),
(1, "Dereham"),
(1, "Devizes"),
(1, "Dewsbury"),
(1, "Didcot"),
(1, "Dinas Powys"),
(1, "Dingwall"),
(1, "Diss"),
(1, "Dolgellau"),
(1, "Dollar"),
(1, "Dolwyddelan"),
(1, "Donaghadee"),
(1, "Doncaster"),
(1, "Dorchester"),
(1, "Dorking"),
(1, "Dornoch"),
(1, "Doune"),
(1, "Dover"),
(1, "Downham Market"),
(1, "Downpatrick"),
(1, "Driffield"),
(1, "Droitwich"),
(1, "Dromore"),
(1, "Dronfield"),
(1, "Drybrook"),
(1, "Dudley"),
(1, "Dukinfield"),
(1, "Dulas"),
(1, "Dulverton"),
(1, "Dumbarton"),
(1, "Dumfries"),
(1, "Dunbar"),
(1, "Dunbeath"),
(1, "Dunblane"),
(1, "Dundee"),
(1, "Dunfermline"),
(1, "Dunfermline (visa Special)"),
(1, "Dungannon"),
(1, "Dunkeld"),
(1, "Dunmow"),
(1, "Dunoon"),
(1, "Duns"),
(1, "Dunstable"),
(1, "Durham"),
(1, "Dursley"),
(1, "Dyffryn Ardudwy"),
(1, "Dymock"),
(1, "Earlston"),
(1, "East Boldon"),
(1, "East Cowes"),
(1, "East Linton"),
(1, "East Molesey"),
(1, "Eastbourne"),
(1, "Eastleigh"),
(1, "Ebbw Vale"),
(1, "Edenbridge"),
(1, "Edgware"),
(1, "Edinburgh"),
(1, "Egham"),
(1, "Egremont"),
(1, "Elgin"),
(1, "Elland"),
(1, "Ellesmere"),
(1, "Ellesmere Port"),
(1, "Ellon"),
(1, "Ely"),
(1, "Emsworth"),
(1, "Enfield"),
(1, "Enniskillen"),
(1, "Epping"),
(1, "Epsom"),
(1, "Erith"),
(1, "Erskine"),
(1, "Esher"),
(1, "Etchingham"),
(1, "Evesham"),
(1, "Exeter"),
(1, "Exmouth"),
(1, "Eye"),
(1, "Eyemouth"),
(1, "Fairbourne"),
(1, "Fairford"),
(1, "Fakenham"),
(1, "Falkirk"),
(1, "Falmouth"),
(1, "Fareham"),
(1, "Faringdon"),
(1, "Farnborough"),
(1, "Farnham"),
(1, "Faversham"),
(1, "Felixstowe"),
(1, "Feltham"),
(1, "Ferndale"),
(1, "Ferndown"),
(1, "Ferryhill"),
(1, "Ferryside"),
(1, "Filey"),
(1, "Fishguard"),
(1, "Fivemiletown"),
(1, "Fleet"),
(1, "Fleetwood"),
(1, "Flint"),
(1, "Fochabers"),
(1, "Folkestone"),
(1, "Fordingbridge"),
(1, "Forfar"),
(1, "Forres"),
(1, "Forsinard"),
(1, "Fort Augustus"),
(1, "Fort William"),
(1, "Fortrose"),
(1, "Fowey"),
(1, "Fraserburgh"),
(1, "Freshwater"),
(1, "Frinton-on-Sea"),
(1, "Frizington"),
(1, "Frodsham"),
(1, "Frome"),
(1, "Fullarton"),
(1, "Gaerwen"),
(1, "Gainsborough"),
(1, "Gairloch"),
(1, "Galashiels"),
(1, "Galston"),
(1, "Garndolbenmaen"),
(1, "Garve"),
(1, "Gateshead"),
(1, "Gatwick"),
(1, "Gerrards Cross"),
(1, "Gillingham"),
(1, "Glasgow"),
(1, "Glastonbury"),
(1, "Glenfinnan"),
(1, "Glenrothes"),
(1, "Glogue"),
(1, "Glossop"),
(1, "Gloucester"),
(1, "Godalming"),
(1, "Godstone"),
(1, "Golspie"),
(1, "Goodwick"),
(1, "Goole"),
(1, "Gordon"),
(1, "Gorebridge"),
(1, "Gosport"),
(1, "Gourock"),
(1, "Grangemouth"),
(1, "Grange-over-Sands"),
(1, "Grantham"),
(1, "Grantown-on-Spey"),
(1, "Gravesend"),
(1, "Grays"),
(1, "Great Missenden"),
(1, "Great Yarmouth"),
(1, "Greenford"),
(1, "Greenhithe"),
(1, "Greenock"),
(1, "Gretna"),
(1, "Grimsby"),
(1, "Guildford"),
(1, "Guisborough"),
(1, "Gullane"),
(1, "Gunnislake"),
(1, "Haddington"),
(1, "Hailsham"),
(1, "Halesowen"),
(1, "Halesworth"),
(1, "Halifax"),
(1, "Halkirk"),
(1, "Halstead"),
(1, "Haltwhistle"),
(1, "Hamilton"),
(1, "Hampton"),
(1, "Harlech"),
(1, "Harleston"),
(1, "Harlow"),
(1, "Harpenden"),
(1, "Harrogate"),
(1, "Harrow"),
(1, "Hartfield"),
(1, "Hartlepool"),
(1, "Harwich"),
(1, "Haslemere"),
(1, "Hassocks"),
(1, "Hastings"),
(1, "Hatfield"),
(1, "Havant"),
(1, "Haverfordwest"),
(1, "Haverhill"),
(1, "Hawes"),
(1, "Hawick"),
(1, "Hayes"),
(1, "Hayle"),
(1, "Hayling Island"),
(1, "Heanor"),
(1, "Heathfield"),
(1, "Hebburn"),
(1, "Hebden Bridge"),
(1, "Heckmondwike"),
(1, "Helensburgh"),
(1, "Helmsdale"),
(1, "Helston"),
(1, "Hemel Hempstead"),
(1, "Henfield"),
(1, "Hengoed"),
(1, "Henley-in-Arden"),
(1, "Henley-on-Thames"),
(1, "Henlow"),
(1, "Hereford"),
(1, "Heriot"),
(1, "Herne Bay"),
(1, "Hertford"),
(1, "Hessle"),
(1, "Hexham"),
(1, "Heywood"),
(1, "High Peak"),
(1, "High Wycombe"),
(1, "Highbridge"),
(1, "Hillsborough"),
(1, "Hinckley"),
(1, "Hindhead"),
(1, "Hinton St. George"),
(1, "Hitchin"),
(1, "Hockley"),
(1, "Hoddesdon"),
(1, "Holmfirth"),
(1, "Holmrook"),
(1, "Holsworthy"),
(1, "Holt"),
(1, "Holyhead"),
(1, "Holywell"),
(1, "Holywood"),
(1, "Honiton"),
(1, "Hook"),
(1, "Hope Valley"),
(1, "Horley"),
(1, "Horncastle"),
(1, "Hornchurch"),
(1, "Hornsea"),
(1, "Houghton le Spring"),
(1, "Hounslow"),
(1, "Hove"),
(1, "Huddersfield"),
(1, "Hull"),
(1, "Humbie"),
(1, "Hungerford"),
(1, "Hunstanton"),
(1, "Huntingdon"),
(1, "Huntly"),
(1, "Hyde"),
(1, "Hythe"),
(1, "Ibstock"),
(1, "Ilford"),
(1, "Ilfracombe"),
(1, "Ilkeston"),
(1, "Ilkley"),
(1, "Ilminster"),
(1, "Immingham"),
(1, "Ingatestone"),
(1, "Innerleithen"),
(1, "Insch"),
(1, "Inveraray"),
(1, "Invergarry"),
(1, "Invergordon"),
(1, "Inverkeithing"),
(1, "Inverness"),
(1, "Inverurie"),
(1, "Ipswich"),
(1, "Irvine"),
(1, "Isle of Barra"),
(1, "Isle of Benbecula"),
(1, "Isle of Bute"),
(1, "Isle of Canna"),
(1, "Isle of Coll"),
(1, "Isle of Colonsay"),
(1, "Isle of Eigg"),
(1, "Isle of Gigha"),
(1, "Isle of Harris"),
(1, "Isle of Iona"),
(1, "Isle of Islay"),
(1, "Isle of Jura"),
(1, "Isle of Lewis"),
(1, "Isle of Mull"),
(1, "Isle of North Uist"),
(1, "Isle of Rum"),
(1, "Isle of Scalpay"),
(1, "Isle of Skye"),
(1, "Isle of South Uist"),
(1, "Isle of Tiree"),
(1, "Isles of Scilly"),
(1, "Isleworth"),
(1, "Iver"),
(1, "Ivybridge"),
(1, "Jarrow"),
(1, "Jedburgh"),
(1, "Johnstone"),
(1, "Juniper Green"),
(1, "Keighley"),
(1, "Keith"),
(1, "Kelso"),
(1, "Kelty"),
(1, "Kendal"),
(1, "Keston"),
(1, "Keswick"),
(1, "Kettering"),
(1, "Kidderminster"),
(1, "Kidlington"),
(1, "Kidwelly"),
(1, "Kilgetty"),
(1, "Killin"),
(1, "Kilmacolm"),
(1, "Kilmarnock"),
(1, "Kinbrace"),
(1, "Kings Langley"),
(1, "King's Lynn"),
(1, "Kingsbridge"),
(1, "Kingston upon Thames"),
(1, "Kingswinford"),
(1, "Kington"),
(1, "Kingussie"),
(1, "Kinlochleven"),
(1, "Kinross"),
(1, "Kirkby Stephen"),
(1, "Kirkby-in-Furness"),
(1, "Kirkcaldy"),
(1, "Kirkcudbright"),
(1, "Kirkliston"),
(1, "Kirknewton"),
(1, "Kirkwall"),
(1, "Kirriemuir"),
(1, "Knaresborough"),
(1, "Knebworth"),
(1, "Knighton"),
(1, "Knottingley"),
(1, "Knutsford"),
(1, "Kyle"),
(1, "Lairg"),
(1, "Lampeter"),
(1, "Lanark"),
(1, "Lancaster"),
(1, "Lancing"),
(1, "Langholm"),
(1, "Langport"),
(1, "Larbert"),
(1, "Larkhall"),
(1, "Larne"),
(1, "Lasswade"),
(1, "Latheron"),
(1, "Lauder"),
(1, "Launceston"),
(1, "Laurencekirk"),
(1, "Leamington Spa"),
(1, "Leatherhead"),
(1, "Lechlade"),
(1, "Ledbury"),
(1, "Leeds"),
(1, "Leek"),
(1, "Lee-on-the-Solent"),
(1, "Leicester"),
(1, "Leigh"),
(1, "Leigh-on-Sea"),
(1, "Leighton Buzzard"),
(1, "Leiston"),
(1, "Leominster"),
(1, "Letchworth Garden City"),
(1, "Leven"),
(1, "Lewes"),
(1, "Leyburn"),
(1, "Leyland"),
(1, "Lichfield"),
(1, "Lifton"),
(1, "Lightwater"),
(1, "Limavady"),
(1, "Lincoln"),
(1, "Lingfield"),
(1, "Linlithgow"),
(1, "Liphook"),
(1, "Lisburn"),
(1, "Liskeard"),
(1, "Liss"),
(1, "Littleborough"),
(1, "Littlehampton"),
(1, "Liverpool"),
(1, "Liversedge"),
(1, "Livingston"),
(1, "Llanarth"),
(1, "Llanbedr"),
(1, "Llanbedrgoch"),
(1, "Llanbrynmair"),
(1, "Llandeilo"),
(1, "Llandinam"),
(1, "Llandovery"),
(1, "Llandrindod Wells"),
(1, "Llandudno"),
(1, "Llandudno Junction"),
(1, "Llandysul"),
(1, "Llanelli"),
(1, "Llanerchymedd"),
(1, "Llanfairfechan"),
(1, "Llanfairpwllgwyngyll"),
(1, "Llanfechain"),
(1, "Llanfyllin"),
(1, "Llanfyrnach"),
(1, "Llangadog"),
(1, "Llangammarch Wells"),
(1, "Llangefni"),
(1, "Llangollen"),
(1, "Llanidloes"),
(1, "Llanon"),
(1, "Llanrhystud"),
(1, "Llanrwst"),
(1, "Llansanffraid"),
(1, "Llantwit Major"),
(1, "Llanwrda"),
(1, "Llanwrtyd Wells"),
(1, "Llanybydder"),
(1, "Llanymynec"),
(1, "Llwyngwril"),
(1, "Loanhead"),
(1, "Lochailort"),
(1, "Lochearnhead"),
(1, "Lochgelly"),
(1, "Lochgilphead"),
(1, "Lochwinnoch"),
(1, "Lockerbie"),
(1, "London"),
(1, "Longfield"),
(1, "Longhope"),
(1, "Longniddry"),
(1, "Looe"),
(1, "Lossiemouth"),
(1, "Lostwithiel"),
(1, "Loughborough"),
(1, "Loughton"),
(1, "Louth"),
(1, "Lowestoft"),
(1, "Ludlow"),
(1, "Luton"),
(1, "Lutterworth"),
(1, "Lybster"),
(1, "Lydbrook"),
(1, "Lydbury North"),
(1, "Lydney"),
(1, "Lyme Regis"),
(1, "Lymington"),
(1, "Lymm"),
(1, "Lyndhurst"),
(1, "Lynmouth"),
(1, "Lynton"),
(1, "Lytham St. Annes"),
(1, "Mablethorpe"),
(1, "Macclesfield"),
(1, "Macduff"),
(1, "Machynlleth"),
(1, "Maesteg"),
(1, "Maghera"),
(1, "Magherafelt"),
(1, "Maidenhead"),
(1, "Maidstone"),
(1, "Maldon"),
(1, "Mallaig"),
(1, "Malmesbury"),
(1, "Malpas"),
(1, "Malton"),
(1, "Malvern"),
(1, "Manchester"),
(1, "Manningtree"),
(1, "Mansfield"),
(1, "Marazion"),
(1, "March"),
(1, "Margate"),
(1, "Marianglas"),
(1, "Market Drayton"),
(1, "Market Harborough"),
(1, "Market Rasen"),
(1, "Markfield"),
(1, "Marlborough"),
(1, "Marlow"),
(1, "Martock"),
(1, "Maryport"),
(1, "Matlock"),
(1, "Mauchline"),
(1, "Mauchline And Catrine"),
(1, "Mayfield"),
(1, "Melksham"),
(1, "Melrose"),
(1, "Melton Constable"),
(1, "Melton Mowbray"),
(1, "Menai Bridge"),
(1, "Menstrie"),
(1, "Merriott"),
(1, "Merthyr Tydfil"),
(1, "Mexborough"),
(1, "Middlesbrough"),
(1, "Middlewich"),
(1, "Midhurst"),
(1, "Milford Haven"),
(1, "Millom"),
(1, "Milltimber"),
(1, "Milnthorpe"),
(1, "Milton Keynes"),
(1, "Mindrum"),
(1, "Minehead"),
(1, "Mirfield"),
(1, "Mitcham"),
(1, "Mitcheldean"),
(1, "Moelfre"),
(1, "Moffat"),
(1, "Mold"),
(1, "Monmouth"),
(1, "Montacute"),
(1, "Montgomery"),
(1, "Montrose"),
(1, "Moor Row"),
(1, "Morden"),
(1, "Morecambe"),
(1, "Moreton-in-Marsh"),
(1, "Morpeth"),
(1, "Motherwell"),
(1, "Mountain Ash"),
(1, "Much Hadham"),
(1, "Much Wenlock"),
(1, "Muir of Ord"),
(1, "Munlochy"),
(1, "Musselburgh"),
(1, "Nairn"),
(1, "Nantwich"),
(1, "Narberth"),
(1, "Neath"),
(1, "Nelson"),
(1, "Neston"),
(1, "Nethy Bridge"),
(1, "New Malden"),
(1, "New Milton"),
(1, "New Quay"),
(1, "New Romney"),
(1, "New Tredegar"),
(1, "Newark"),
(1, "Newbiggin-by-the-Sea"),
(1, "Newbridge"),
(1, "Newbury"),
(1, "Newcastle"),
(1, "Newcastle Emlyn"),
(1, "Newcastle upon Tyne"),
(1, "Newcastleton"),
(1, "Newent"),
(1, "Newhaven"),
(1, "Newmarket"),
(1, "Newmilns"),
(1, "Newnham"),
(1, "Newport"),
(1, "Newport Pagnell"),
(1, "Newport-on-Tay"),
(1, "Newquay"),
(1, "Newry (south Armagh Section)"),
(1, "Newry (south Down Section)"),
(1, "Newton Abbot"),
(1, "Newton Aycliffe"),
(1, "Newton Stewart"),
(1, "Newton-le-Willows"),
(1, "Newtonmore"),
(1, "Newtown"),
(1, "Newtownabbey"),
(1, "Newtownards"),
(1, "Non-Geographic"),
(1, "Normanton"),
(1, "North Berwick"),
(1, "North Ferriby"),
(1, "North Shields"),
(1, "North Tawton"),
(1, "North Walsham"),
(1, "Northallerton"),
(1, "Northampton"),
(1, "Northolt"),
(1, "Northwich"),
(1, "Northwood"),
(1, "Norwich"),
(1, "Nottingham"),
(1, "Nuneaton"),
(1, "Oakham"),
(1, "Oban"),
(1, "Okehampton"),
(1, "Oldbury"),
(1, "Oldham"),
(1, "Olney"),
(1, "Omagh"),
(1, "Ongar"),
(1, "Orkney"),
(1, "Ormskirk"),
(1, "Orpington"),
(1, "Ossett"),
(1, "Oswestry"),
(1, "Otley"),
(1, "Ottery St. Mary"),
(1, "Oxford"),
(1, "Oxted"),
(1, "Padstow"),
(1, "Paignton"),
(1, "Paisley"),
(1, "Par"),
(1, "Pathhead"),
(1, "Patna And Drongan"),
(1, "Peacehaven"),
(1, "Peebles"),
(1, "Pembroke"),
(1, "Pembroke Dock"),
(1, "Penarth"),
(1, "Pencader"),
(1, "Penicuik"),
(1, "Penmaenmawr"),
(1, "Penrhyndeudraeth"),
(1, "Penrith"),
(1, "Penryn"),
(1, "Pentraeth"),
(1, "Pentre"),
(1, "Penysarn"),
(1, "Penzance"),
(1, "Perranporth"),
(1, "Pershore"),
(1, "Perth"),
(1, "Peterborough"),
(1, "Peterculter"),
(1, "Peterhead"),
(1, "Peterlee"),
(1, "Petersfield"),
(1, "Petworth"),
(1, "Pevensey"),
(1, "Pewsey"),
(1, "Pickering"),
(1, "Pinner"),
(1, "Pitlochry"),
(1, "Plockton"),
(1, "Plymouth"),
(1, "Polegate"),
(1, "Pontefract"),
(1, "Pontyclun"),
(1, "Pontypool"),
(1, "Pontypridd"),
(1, "Poole"),
(1, "Port Glasgow"),
(1, "Port Isaac"),
(1, "Port Talbot"),
(1, "Porth"),
(1, "Porthcawl"),
(1, "Porthmadog"),
(1, "Portland"),
(1, "Portree"),
(1, "Portrush"),
(1, "Portsmouth"),
(1, "Portstewart"),
(1, "Potters Bar"),
(1, "Poulton-le-Fylde"),
(1, "Prenton"),
(1, "Prescot"),
(1, "Prestatyn"),
(1, "Presteigne"),
(1, "Preston"),
(1, "Prestonpans"),
(1, "Princes Risborough"),
(1, "Prudhoe"),
(1, "Pudsey"),
(1, "Pulborough"),
(1, "Purfleet"),
(1, "Purley"),
(1, "Pwllheli"),
(1, "Queenborough"),
(1, "Radlett"),
(1, "Radstock"),
(1, "Rainham"),
(1, "Ramsgate"),
(1, "Ravenglass"),
(1, "Rayleigh"),
(1, "Reading"),
(1, "Redcar"),
(1, "Redditch"),
(1, "Redhill"),
(1, "Redruth"),
(1, "Reigate"),
(1, "Renfrew"),
(1, "Retford"),
(1, "Rhayader"),
(1, "Rhosgoch"),
(1, "Rhosneigr"),
(1, "Rhyl"),
(1, "Richmond"),
(1, "Rickmansworth"),
(1, "Riding Mill"),
(1, "Ringwood"),
(1, "Ripley"),
(1, "Ripon"),
(1, "Robertsbridge"),
(1, "Rochdale"),
(1, "Rochester"),
(1, "Rochford"),
(1, "Rogart"),
(1, "Romford"),
(1, "Romney Marsh"),
(1, "Romsey"),
(1, "Rosewell"),
(1, "Roslin"),
(1, "Rossendale"),
(1, "Ross-on-Wye"),
(1, "Rotherham"),
(1, "Rowland's Castle"),
(1, "Rowlands Gill"),
(1, "Rowley Regis"),
(1, "Roy Bridge"),
(1, "Royston"),
(1, "Ruardean"),
(1, "Rugby"),
(1, "Rugeley"),
(1, "Ruislip"),
(1, "Runcorn"),
(1, "Rushden"),
(1, "Ruthin"),
(1, "Ryde"),
(1, "Rye"),
(1, "Ryton"),
(1, "Saffron Walden"),
(1, "Salcombe"),
(1, "Sale"),
(1, "Salford"),
(1, "Salisbury"),
(1, "Saltash"),
(1, "Saltburn-by-the-Sea"),
(1, "Sandbach"),
(1, "Sandhurst"),
(1, "Sandown"),
(1, "Sandringham"),
(1, "Sandwich"),
(1, "Sandy"),
(1, "Sanquhar"),
(1, "Saundersfoot"),
(1, "Sawbridgeworth"),
(1, "Saxmundham"),
(1, "Scarborough"),
(1, "Scunthorpe"),
(1, "Seaford"),
(1, "Seaham"),
(1, "Seahouses"),
(1, "Seascale"),
(1, "Seaton"),
(1, "Seaview"),
(1, "Sedbergh"),
(1, "Selby"),
(1, "Selkirk"),
(1, "Settle"),
(1, "Sevenoaks"),
(1, "Shaftesbury"),
(1, "Shanklin"),
(1, "Sheerness"),
(1, "Sheffield"),
(1, "Shefford"),
(1, "Shepperton"),
(1, "Shepton Mallet"),
(1, "Sherborne"),
(1, "Sheringham"),
(1, "Shetland"),
(1, "Shifnal"),
(1, "Shildon"),
(1, "Shipley"),
(1, "Shipston-on-Stour"),
(1, "Shoreham-by-Sea"),
(1, "Shotts"),
(1, "Shrewsbury"),
(1, "Sidcup"),
(1, "Sidmouth"),
(1, "Sittingbourne"),
(1, "Skegness"),
(1, "Skelmersdale"),
(1, "Skelmorlie"),
(1, "Skipton"),
(1, "Sleaford"),
(1, "Slough"),
(1, "Smethwick"),
(1, "Snodland"),
(1, "Solihull"),
(1, "Somerton"),
(1, "South Brent"),
(1, "South Croydon"),
(1, "South Molton"),
(1, "South Ockendon"),
(1, "South Petherton"),
(1, "South Queensferry"),
(1, "South Shields"),
(1, "Southall"),
(1, "Southam"),
(1, "Southampton"),
(1, "Southend-on-Sea"),
(1, "Southminster"),
(1, "Southport"),
(1, "Southsea"),
(1, "Southwell"),
(1, "Southwold"),
(1, "Sowerby Bridge"),
(1, "Spalding"),
(1, "Spean Bridge"),
(1, "Spennymoor"),
(1, "Spilsby"),
(1, "Springside"),
(1, "St. Agnes"),
(1, "St. Albans"),
(1, "St. Andrews"),
(1, "St. Asaph"),
(1, "St. Austell"),
(1, "St. Bees"),
(1, "St. Columb"),
(1, "St. Helens"),
(1, "St. Ives"),
(1, "St. Leonards-on-Sea"),
(1, "St. Neots"),
(1, "Stafford"),
(1, "Staines-upon-Thames"),
(1, "Stalybridge"),
(1, "Stamford"),
(1, "Stanford-le-Hope"),
(1, "Stanley"),
(1, "Stanmore"),
(1, "Stansted"),
(1, "Stevenage"),
(1, "Steyning"),
(1, "Stirling"),
(1, "Stockbridge"),
(1, "Stockport"),
(1, "Stocksfield"),
(1, "Stockton-on-Tees"),
(1, "Stoke-on-Trent"),
(1, "Stoke-Sub-Hamdon"),
(1, "Stone"),
(1, "Stonehaven"),
(1, "Stonehouse"),
(1, "Stornoway"),
(1, "Stourbridge"),
(1, "Stourport-on-Severn"),
(1, "Stowmarket"),
(1, "Strabane"),
(1, "Stranraer"),
(1, "Stratford-upon-Avon"),
(1, "Strathaven"),
(1, "Strathcarron"),
(1, "Strathdon"),
(1, "Strathpeffer"),
(1, "Street"),
(1, "Strome Ferry"),
(1, "Stromness"),
(1, "Stroud"),
(1, "Studley"),
(1, "Sturminster Newton"),
(1, "Sudbury"),
(1, "Sunbury-on-Thames"),
(1, "Sunderland"),
(1, "Surbiton"),
(1, "Sutton"),
(1, "Sutton Coldfield"),
(1, "Sutton-in-Ashfield"),
(1, "Swadlincote"),
(1, "Swaffham"),
(1, "Swanage"),
(1, "Swanley"),
(1, "Swanscombe"),
(1, "Swansea"),
(1, "Swindon"),
(1, "Tadcaster"),
(1, "Tadley"),
(1, "Tadworth"),
(1, "Tain"),
(1, "Talsarnau"),
(1, "Talybont"),
(1, "Tamworth"),
(1, "Tarbert"),
(1, "Tarporley"),
(1, "Taunton"),
(1, "Tavistock"),
(1, "Taynuilt"),
(1, "Tayport"),
(1, "Teddington"),
(1, "Teignmouth"),
(1, "Telford"),
(1, "Templecombe"),
(1, "Tenbury Wells"),
(1, "Tenby"),
(1, "Tenterden"),
(1, "Tetbury"),
(1, "Tewkesbury"),
(1, "Thame"),
(1, "Thames Ditton"),
(1, "Thatcham"),
(1, "Thetford"),
(1, "Thirsk"),
(1, "Thornhill"),
(1, "Thornton Heath"),
(1, "Thornton-Cleveleys"),
(1, "Thurso"),
(1, "Tidworth"),
(1, "Tighnabruaich"),
(1, "Tilbury"),
(1, "Tillicoultry"),
(1, "Tintagel"),
(1, "Tipton"),
(1, "Tiverton"),
(1, "Todmorden"),
(1, "Tonbridge"),
(1, "Tonypandy"),
(1, "Torpoint"),
(1, "Torquay"),
(1, "Torrington"),
(1, "Totland Bay"),
(1, "Totnes"),
(1, "Towcester"),
(1, "Tranent"),
(1, "Tredegar"),
(1, "Trefriw"),
(1, "Tregaron"),
(1, "Treharris"),
(1, "Treorchy"),
(1, "Trimdon Station"),
(1, "Tring"),
(1, "Trowbridge"),
(1, "Truro"),
(1, "Tunbridge Wells"),
(1, "Turriff"),
(1, "Twickenham"),
(1, "Ty Croes"),
(1, "Tyn-y-Gongl"),
(1, "Tywyn"),
(1, "Uckfield"),
(1, "Ulceby"),
(1, "Ullapool"),
(1, "Ulverston"),
(1, "Umberleigh"),
(1, "Upminster"),
(1, "Usk"),
(1, "Uttoxeter"),
(1, "Uxbridge"),
(1, "Ventnor"),
(1, "Verwood"),
(1, "Virginia Water"),
(1, "Wadebridge"),
(1, "Wadhurst"),
(1, "Wakefield"),
(1, "Walkerburn"),
(1, "Wallasey"),
(1, "Wallingford"),
(1, "Wallington"),
(1, "Wallsend"),
(1, "Walsall"),
(1, "Walsingham"),
(1, "Waltham Abbey"),
(1, "Waltham Cross"),
(1, "Walton on the Naze"),
(1, "Walton-on-Thames"),
(1, "Wantage"),
(1, "Ware"),
(1, "Wareham"),
(1, "Warlingham"),
(1, "Warminster"),
(1, "Warrington"),
(1, "Warwick"),
(1, "Washington"),
(1, "Watchet"),
(1, "Waterlooville"),
(1, "Watford"),
(1, "Watlington"),
(1, "Wedmore"),
(1, "Wednesbury"),
(1, "Welling"),
(1, "Wellingborough"),
(1, "Wellington"),
(1, "Wells"),
(1, "Wells-Next-the-Sea"),
(1, "Welshpool"),
(1, "Welwyn"),
(1, "Welwyn Garden City"),
(1, "Wembley"),
(1, "Wemyss Bay"),
(1, "West Bromwich"),
(1, "West Byfleet"),
(1, "West Calder"),
(1, "West Drayton"),
(1, "West Linton"),
(1, "West Malling"),
(1, "West Molesey"),
(1, "West Wickham"),
(1, "Westbury"),
(1, "Westbury-on-Severn"),
(1, "Westcliff-on-Sea"),
(1, "Westerham"),
(1, "Westgate-on-Sea"),
(1, "Westhill"),
(1, "Weston-Super-Mare"),
(1, "Wetherby"),
(1, "Weybridge"),
(1, "Weymouth"),
(1, "Whitby"),
(1, "Whitchurch"),
(1, "Whitehaven"),
(1, "Whitland"),
(1, "Whitley Bay"),
(1, "Whitstable"),
(1, "Wick"),
(1, "Wickford"),
(1, "Widnes"),
(1, "Wigan"),
(1, "Wigston"),
(1, "Wigton"),
(1, "Willenhall"),
(1, "Wilmslow"),
(1, "Wimborne"),
(1, "Wincanton"),
(1, "Winchelsea"),
(1, "Winchester"),
(1, "Windermere"),
(1, "Windlesham"),
(1, "Windsor"),
(1, "Wingate"),
(1, "Winkleigh"),
(1, "Winscombe"),
(1, "Winsford"),
(1, "Wirral"),
(1, "Wisbech"),
(1, "Wishaw"),
(1, "Witham"),
(1, "Withernsea"),
(1, "Witney"),
(1, "Woking"),
(1, "Wokingham"),
(1, "Wolverhampton"),
(1, "Woodbridge"),
(1, "Woodford Green"),
(1, "Woodhall Spa"),
(1, "Woodstock"),
(1, "Woolacombe"),
(1, "Wooler"),
(1, "Worcester"),
(1, "Worcester Park"),
(1, "Workington"),
(1, "Worksop"),
(1, "Worthing"),
(1, "Wotton-under-Edge"),
(1, "Wrexham"),
(1, "Wylam"),
(1, "Wymondham"),
(1, "Y Felinheli"),
(1, "Yarm"),
(1, "Yarmouth"),
(1, "Yateley"),
(1, "Yelverton"),
(1, "Yeovil"),
(1, "York"),
(1, "Ystrad Meurig"),
(2, "Carlow"),
(2, "Cavan"),
(2, "Clare"),
(2, "Cork"),
(2, "Derry"),
(2, "Donegal"),
(2, "Down"),
(2, "Dublin"),
(2, "Fermanagh"),
(2, "Galway"),
(2, "Kerry"),
(2, "Kildare"),
(2, "Kilkenny"),
(2, "Laois"),
(2, "Leitrim"),
(2, "Limerick"),
(2, "Longford"),
(2, "Mayo"),
(2, "Meath"),
(2, "Monaghan"),
(2, "Offaly"),
(2, "Roscommon"),
(2, "Sligo"),
(2, "Tipperary"),
(2, "Tyrone"),
(2, "Waterford"),
(2, "Westmeath"),
(2, "Wexford"),
(2, "Wicklow");

INSERT INTO institute_list(countryCode, instituteName) VALUES
(1, "Abertay University"),
(1, "Aberystwyth University"),
(1, "AECC University College"),
(1, "Anglia Ruskin University"),
(1, "Arden University"),
(1, "Ashridge Executive Education"),
(1, "Aston University"),
(1, "Bangor University"),
(1, "Bath Spa University"),
(1, "Birkbeck, University of London"),
(1, "Birmingham City University"),
(1, "Bishop Grosseteste University"),
(1, "Bournemouth University"),
(1, "BPP University"),
(1, "Brunel University"),
(1, "Buckinghamshire New University"),
(1, "Canterbury Christ Church University"),
(1, "Cardiff Metropolitan University"),
(1, "Cardiff University"),
(1, "City, University of London"),
(1, "Courtauld Institute of Art"),
(1, "Coventry University"),
(1, "Cranfield University"),
(1, "De Montfort University"),
(1, "Durham University"),
(1, "Edge Hill University"),
(1, "Edinburgh Napier University"),
(1, "Falmouth University"),
(1, "Glasgow Caledonian University"),
(1, "Goldsmiths, University of London"),
(1, "Guildhall School of Music and Drama"),
(1, "Harper Adams University"),
(1, "Hartpury College"),
(1, "Hartpury University"),
(1, "Heriot-Watt University"),
(1, "Imperial College London"),
(1, "Institute of Cancer Research"),
(1, "Keele University"),
(1, "King's College London"),
(1, "Kingston University"),
(1, "Lancaster University"),
(1, "Leeds Arts University"),
(1, "Leeds Beckett University"),
(1, "Leeds Trinity University"),
(1, "Liverpool Hope University"),
(1, "Liverpool John Moores University"),
(1, "Liverpool School of Tropical Medicine"),
(1, "London Business School"),
(1, "London Institute of Banking and Finance"),
(1, "London Metropolitan University"),
(1, "London School of Economics and Political Science"),
(1, "London School of Hygiene and Tropical Medicine"),
(1, "London South Bank University"),
(1, "Loughborough University"),
(1, "Manchester Metropolitan University"),
(1, "Middlesex University"),
(1, "NCG"),
(1, "Newcastle University"),
(1, "Newman University"),
(1, "Northumbria University"),
(1, "Norwich University of the Arts"),
(1, "Nottingham Trent University"),
(1, "Oxford Brookes University"),
(1, "Plymouth Marjon University"),
(1, "Queen Margaret University"),
(1, "Queen Mary, University of London"),
(1, "Queen's University Belfast"),
(1, "Ravensbourne University London"),
(1, "Regent's University London"),
(1, "Richmond, The American International University in London"),
(1, "Roehampton University"),
(1, "Rose Bruford College of Theatre and Performance"),
(1, "Royal Academy of Music"),
(1, "Royal Agricultural University"),
(1, "Royal Central School of Speech and Drama"),
(1, "Royal College of Art"),
(1, "Royal College of Music"),
(1, "Royal Conservatoire of Scotland"),
(1, "Royal Holloway, University of London"),
(1, "Royal Northern College of Music"),
(1, "Royal Veterinary College"),
(1, "School of Oriental and African Studies"),
(1, "Sheffield Hallam University"),
(1, "Solent University"),
(1, "St George's, University of London"),
(1, "St Mary's University"),
(1, "Staffordshire University"),
(1, "Swansea University"),
(1, "Teesside University"),
(1, "The Arts University Bournemouth"),
(1, "The Open University"),
(1, "The Robert Gordon University"),
(1, "The King's Building of King's College London"),
(1, "Trinity Laban Conservatoire of Music and Dance"),
(1, "Ulster University"),
(1, "University College Birmingham"),
(1, "University College London"),
(1, "University College of Estate Management"),
(1, "University College of Osteopathy"),
(1, "University for the Creative Arts"),
(1, "University of Aberdeen"),
(1, "University of Bath"),
(1, "University of Bedfordshire"),
(1, "University of Birmingham"),
(1, "University of Bolton"),
(1, "University of Bradford"),
(1, "University of Brighton"),
(1, "University of Bristol"),
(1, "University of Buckingham"),
(1, "University of Cambridge"),
(1, "University of Central Lancashire"),
(1, "University of Chester"),
(1, "University of Chichester"),
(1, "University of Cumbria"),
(1, "University of Derby"),
(1, "University of Dundee"),
(1, "University of East Anglia"),
(1, "University of East London"),
(1, "University of Edinburgh"),
(1, "University of Essex"),
(1, "University of Exeter"),
(1, "University of Glasgow"),
(1, "University of Gloucestershire"),
(1, "University of Greenwich"),
(1, "University of Hertfordshire"),
(1, "University of Huddersfield"),
(1, "University of Hull"),
(1, "University of Kent"),
(1, "University of Law"),
(1, "University of Leeds"),
(1, "University of Leicester"),
(1, "University of Lincoln"),
(1, "University of Liverpool"),
(1, "University of London"),
(1, "University of Manchester"),
(1, "University of Northampton"),
(1, "University of Nottingham"),
(1, "University of Oxford"),
(1, "University of Plymouth"),
(1, "University of Portsmouth"),
(1, "University of Reading"),
(1, "University of Salford"),
(1, "University of Sheffield"),
(1, "University of South Wales"),
(1, "University of Southampton"),
(1, "University of St Andrews"),
(1, "University of Stirling"),
(1, "University of Strathclyde"),
(1, "University of Suffolk"),
(1, "University of Sunderland"),
(1, "University of Surrey"),
(1, "University of Sussex"),
(1, "University of the Arts London"),
(1, "University of the Highlands & Islands"),
(1, "University of the West of England"),
(1, "University of the West of Scotland"),
(1, "University of Wales"),
(1, "University of Wales Trinity Saint David"),
(1, "University of Warwick"),
(1, "University of West London"),
(1, "University of Westminster"),
(1, "University of Winchester"),
(1, "University of Wolverhampton"),
(1, "University of Worcester"),
(1, "University of York"),
(1, "Wrexham Glyndŵr University"),
(1, "Writtle University College"),
(1, "York St John University"),
(2, "Dublin City University"),
(2, "Maynooth University"),
(2, "National University of Ireland, Galway"),
(2, "Royal College of Surgeons in Ireland"),
(2, "Technological University Dublin"),
(2, "Trinity College Dublin, the University of Dublin"),
(2, "University College Cork"),
(2, "University College Dublin"),
(2, "University of Limerick");

INSERT INTO studyField_list(studyFieldName) VALUES
("Arts & Humanities"),
("Engineering & Technology"),
("Life Sciences & Medicine"),
("Natural Sciences"),
("Social Sciences & Management"),
("Professional Qualification");

INSERT INTO studySubject_list(studyFieldCode, studySubjectName) VALUES
(1, "Archaeology"),
(1, "Architecture"),
(1, "Art & Design"),
(1, "Classics & Ancient History"),
(1, "English Language & Literature"),
(1, "History"),
(1, "Linguistics"),
(1, "Modern Languages"),
(1, "Performing Arts"),
(1, "Philosophy"),
(1, "Theology, Divinity & Religious Studies"),
(2, "Computer Science & Information Systems"),
(2, "Engineering Chemical"),
(2, "Engineering Civil & Structural"),
(2, "Engineering Electrical & Electronic"),
(2, "Engineering Mechanical, Aeronautical & Manufacturing"),
(2, "Engineering Mineral & Mining"),
(3, "Agriculture & Forestry"),
(3, "Anatomy & Physiology"),
(3, "Biological Sciences"),
(3, "Dentistry"),
(3, "Medicine"),
(3, "Nursing"),
(3, "Pharmacy & Pharmacology"),
(3, "Psychology"),
(3, "Veterinary Science"),
(4, "Chemistry"),
(4, "Earth & Marine Sciences"),
(4, "Environmental Sciences"),
(4, "Geography"),
(4, "Materials Science"),
(4, "Mathematics"),
(4, "Physics & Astronomy"),
(5, "Accounting & Finance"),
(5, "Anthropology"),
(5, "Business & Management Studies"),
(5, "Communication & Media Studies"),
(5, "Development Studies"),
(5, "Economics & Econometrics"),
(5, "Education & Training"),
(5, "Hospitality & Leisure Management"),
(5, "Law"),
(5, "Library & Information Management"),
(5, "Politics & International Studies"),
(5, "Social Policy & Administration"),
(5, "Sociology"),
(5, "Sports-related Subjects"),
(5, "Statistics & Operational Research"),
(6, "ACCA - Association of Chartered Certified Accountants");
