INSERT INTO userType_list(userTypeName) VALUES
("Student"),
("Admin_00"),
("Developer");

INSERT INTO gender_list(genderName) VALUES
("Male"),
("Female");

INSERT INTO state_list(stateName) VALUES
("Johor"),
("Kedah"),
("Kelantan"),
("Melaka"),
("Negeri Sembilan"),
("Pahang"),
("Perak"),
("Perlis"),
("Pulau Pinang"),
("Sabah"),
("Sarawak"),
("Selangor"),
("Terengganu"),
("W.P. Kuala Lumpur"),
("W.P. Labuan"),
("W.P. Putrajaya"),
("Others");

INSERT INTO ethnicity_list(ethnicityName) VALUES
("Malay"),
("Orang Asli"),
("Bumiputera Sabah"),
("Bumiputera Sarawak"),
("Chinese"),
("Indian"),
("Others");

INSERT INTO studyLevel_list(studyLevelName) VALUES
("Professional Qualification"),
("Bachelor’s Degree"),
("Master’s Degree"),
("Doctorate");

INSERT INTO country_list(countryName) VALUES
("United Kingdom"),
("Ireland");

INSERT INTO institute_list(countryCode, instituteName) VALUES
(1, "Abertay University"),
(1, "Aberystwyth University"),
(1, "AECC University College"),
(1, "Anglia Ruskin University"),
(1, "Arden University"),
(1, "Ashridge Executive Education"),
(1, "Aston University"),
(1, "Bangor University"),
(1, "Bath Spa University"),
(1, "Birkbeck, University of London"),
(1, "Birmingham City University"),
(1, "Bishop Grosseteste University"),
(1, "Bournemouth University"),
(1, "BPP University"),
(1, "Brunel University"),
(1, "Buckinghamshire New University"),
(1, "Canterbury Christ Church University"),
(1, "Cardiff Metropolitan University"),
(1, "Cardiff University"),
(1, "City, University of London"),
(1, "Courtauld Institute of Art"),
(1, "Coventry University"),
(1, "Cranfield University"),
(1, "De Montfort University"),
(1, "Durham University"),
(1, "Edge Hill University"),
(1, "Edinburgh Napier University"),
(1, "Falmouth University"),
(1, "Glasgow Caledonian University"),
(1, "Goldsmiths, University of London"),
(1, "Guildhall School of Music and Drama"),
(1, "Harper Adams University"),
(1, "Hartpury College"),
(1, "Hartpury University"),
(1, "Heriot-Watt University"),
(1, "Imperial College London"),
(1, "Institute of Cancer Research"),
(1, "Keele University"),
(1, "King's College London"),
(1, "Kingston University"),
(1, "Lancaster University"),
(1, "Leeds Arts University"),
(1, "Leeds Beckett University"),
(1, "Leeds Trinity University"),
(1, "Liverpool Hope University"),
(1, "Liverpool John Moores University"),
(1, "Liverpool School of Tropical Medicine"),
(1, "London Business School"),
(1, "London Institute of Banking and Finance"),
(1, "London Metropolitan University"),
(1, "London School of Economics and Political Science"),
(1, "London School of Hygiene and Tropical Medicine"),
(1, "London South Bank University"),
(1, "Loughborough University"),
(1, "Manchester Metropolitan University"),
(1, "Middlesex University"),
(1, "NCG"),
(1, "Newcastle University"),
(1, "Newman University"),
(1, "Northumbria University"),
(1, "Norwich University of the Arts"),
(1, "Nottingham Trent University"),
(1, "Oxford Brookes University"),
(1, "Plymouth Marjon University"),
(1, "Queen Margaret University"),
(1, "Queen Mary, University of London"),
(1, "Queen's University Belfast"),
(1, "Ravensbourne University London"),
(1, "Regent's University London"),
(1, "Richmond, The American International University in London"),
(1, "Roehampton University"),
(1, "Rose Bruford College of Theatre and Performance"),
(1, "Royal Academy of Music"),
(1, "Royal Agricultural University"),
(1, "Royal Central School of Speech and Drama"),
(1, "Royal College of Art"),
(1, "Royal College of Music"),
(1, "Royal Conservatoire of Scotland"),
(1, "Royal Holloway, University of London"),
(1, "Royal Northern College of Music"),
(1, "Royal Veterinary College"),
(1, "School of Oriental and African Studies"),
(1, "Sheffield Hallam University"),
(1, "Solent University"),
(1, "St George's, University of London"),
(1, "St Mary's University"),
(1, "Staffordshire University"),
(1, "Swansea University"),
(1, "Teesside University"),
(1, "The Arts University Bournemouth"),
(1, "The Open University"),
(1, "The Robert Gordon University"),
(1, "The King's Building of King's College London"),
(1, "Trinity Laban Conservatoire of Music and Dance"),
(1, "Ulster University"),
(1, "University College Birmingham"),
(1, "University College London"),
(1, "University College of Estate Management"),
(1, "University College of Osteopathy"),
(1, "University for the Creative Arts"),
(1, "University of Aberdeen"),
(1, "University of Bath"),
(1, "University of Bedfordshire"),
(1, "University of Birmingham"),
(1, "University of Bolton"),
(1, "University of Bradford"),
(1, "University of Brighton"),
(1, "University of Bristol"),
(1, "University of Buckingham"),
(1, "University of Cambridge"),
(1, "University of Central Lancashire"),
(1, "University of Chester"),
(1, "University of Chichester"),
(1, "University of Cumbria"),
(1, "University of Derby"),
(1, "University of Dundee"),
(1, "University of East Anglia"),
(1, "University of East London"),
(1, "University of Edinburgh"),
(1, "University of Essex"),
(1, "University of Exeter"),
(1, "University of Glasgow"),
(1, "University of Gloucestershire"),
(1, "University of Greenwich"),
(1, "University of Hertfordshire"),
(1, "University of Huddersfield"),
(1, "University of Hull"),
(1, "University of Kent"),
(1, "University of Law"),
(1, "University of Leeds"),
(1, "University of Leicester"),
(1, "University of Lincoln"),
(1, "University of Liverpool"),
(1, "University of London"),
(1, "University of Manchester"),
(1, "University of Northampton"),
(1, "University of Nottingham"),
(1, "University of Oxford"),
(1, "University of Plymouth"),
(1, "University of Portsmouth"),
(1, "University of Reading"),
(1, "University of Salford"),
(1, "University of Sheffield"),
(1, "University of South Wales"),
(1, "University of Southampton"),
(1, "University of St Andrews"),
(1, "University of Stirling"),
(1, "University of Strathclyde"),
(1, "University of Suffolk"),
(1, "University of Sunderland"),
(1, "University of Surrey"),
(1, "University of Sussex"),
(1, "University of the Arts London"),
(1, "University of the Highlands & Islands"),
(1, "University of the West of England"),
(1, "University of the West of Scotland"),
(1, "University of Wales"),
(1, "University of Wales Trinity Saint David"),
(1, "University of Warwick"),
(1, "University of West London"),
(1, "University of Westminster"),
(1, "University of Winchester"),
(1, "University of Wolverhampton"),
(1, "University of Worcester"),
(1, "University of York"),
(1, "Wrexham Glyndŵr University"),
(1, "Writtle University College"),
(1, "York St John University"),
(2, "Dublin City University"),
(2, "Maynooth University"),
(2, "National University of Ireland, Galway"),
(2, "Royal College of Surgeons in Ireland"),
(2, "Technological University Dublin"),
(2, "Trinity College Dublin, the University of Dublin"),
(2, "University College Cork"),
(2, "University College Dublin"),
(2, "University of Limerick");

INSERT INTO studyField_list(studyFieldName) VALUES
("Arts & Humanities"),
("Engineering & Technology"),
("Life Sciences & Medicine"),
("Natural Sciences"),
("Social Sciences & Management"),
("Professional Qualification");

INSERT INTO studySubject_list(studyFieldCode, studySubjectName) VALUES
(1, "Archaeology"),
(1, "Architecture"),
(1, "Art & Design"),
(1, "Classics & Ancient History"),
(1, "English Language & Literature"),
(1, "History"),
(1, "Linguistics"),
(1, "Modern Languages"),
(1, "Performing Arts"),
(1, "Philosophy"),
(1, "Theology, Divinity & Religious Studies"),
(2, "Computer Science & Information Systems"),
(2, "Engineering Chemical"),
(2, "Engineering Civil & Structural"),
(2, "Engineering Electrical & Electronic"),
(2, "Engineering Mechanical, Aeronautical & Manufacturing"),
(2, "Engineering Mineral & Mining"),
(3, "Agriculture & Forestry"),
(3, "Anatomy & Physiology"),
(3, "Biological Sciences"),
(3, "Dentistry"),
(3, "Medicine"),
(3, "Nursing"),
(3, "Pharmacy & Pharmacology"),
(3, "Psychology"),
(3, "Veterinary Science"),
(4, "Chemistry"),
(4, "Earth & Marine Sciences"),
(4, "Environmental Sciences"),
(4, "Geography"),
(4, "Materials Science"),
(4, "Mathematics"),
(4, "Physics & Astronomy"),
(5, "Accounting & Finance"),
(5, "Anthropology"),
(5, "Business & Management Studies"),
(5, "Communication & Media Studies"),
(5, "Development Studies"),
(5, "Economics & Econometrics"),
(5, "Education & Training"),
(5, "Hospitality & Leisure Management"),
(5, "Law"),
(5, "Library & Information Management"),
(5, "Politics & International Studies"),
(5, "Social Policy & Administration"),
(5, "Sociology"),
(5, "Sports-related Subjects"),
(5, "Statistics & Operational Research"),
(6, "ACCA - Association of Chartered Certified Accountants");





